from binance.client import Client
from decimal import Decimal
import graph
import json
import time

pairs = "BNB/USDT,ETH/USDT,BTC/PAX,LTC/USDT,XRP/USDT,XRP/BTC,EVX/BTC,BTC/USDC,LINK/BTC,ADA/BTC,BAT/BTC,BCHABC/BTC,TUSD/USDT,ADA/USDT,BTC/TUSD,OAX/BTC,NEO/USDT,ERD/BTC,ETH/PAX,FET/BTC,ALGO/USDT,PPT/BTC,ANKR/BTC,MTL/BTC,NEBL/BTC,ONE/BTC,ETH/USDC,DUSK/BTC,BTT/USDT,ERD/USDT,BNB/ETH,XLM/BTC,AGI/BTC,IOTA/BTC,DLT/BTC,REN/BNB,EOS/PAX,NANO/USDT,MITH/BTC,ETC/BTC,ATOM/USDT,ENJ/BTC,EVX/ETH,ARK/BTC,SYS/BTC,VET/USDT,BNB/USDC,ICX/USDT,ZRX/BTC,ONE/USDT,TRX/ETH,TNT/BTC,XMR/USDT,NPXS/BTC,DUSK/USDT,WAN/BTC,WABI/BTC,ERD/BNB,BNB/TUSD,LTC/ETH,ARN/BTC,VIB/BTC,RVN/BNB,QTUM/BTC,LTC/USDC,BCHABC/USDC,LTC/BNB,STRAT/BTC,EOS/BNB,BAT/BNB,IOTX/BTC,FUEL/BTC,ARDR/BTC,HOT/ETH,VIBE/BTC,CMT/BTC,NULS/BTC,BCHABC/TUSD,FET/BNB,NEO/ETH,LSK/BTC,APPC/BTC,KMD/BTC,POLY/BTC,GRS/BTC,INS/BTC,SNM/BTC,STEEM/BTC,HOT/BTC,ENG/BTC,ADA/BNB,TFUEL/USDT,NAS/BTC,MITH/USDT,BNB/PAX,FTM/BNB,VIA/BTC,POWR/BTC,WAVES/USDT,DASH/USDT,XMR/ETH,LINK/USDC,DOGE/USDT,OST/BTC,FUN/BTC,FUEL/ETH,DNT/BTC,OMG/USDT,BTT/BTC,PPT/ETH,OAX/ETH,LOOM/BTC,XRP/USDC,TRX/USDC,NCASH/ETH,XZC/BTC,GNT/BTC,AION/ETH,GTO/BNB,MCO/ETH,ONE/BNB,ADA/USDC,KNC/ETH,STORJ/BTC,GTO/BTC,NAV/BTC,DGD/BTC,IOTA/BNB,ANKR/BNB,WAN/ETH,ADA/TUSD,TNB/BTC,GAS/BTC,VET/ETH,NEO/USDC,XRP/PAX,NEO/BNB,ONG/BTC,LINK/TUSD,ENJ/ETH,XRP/TUSD,VET/BNB,THETA/ETH,DASH/ETH,CELR/BNB,ARN/ETH,REQ/BTC,ONG/USDT,YOYO/BTC,XLM/ETH,ADA/PAX,XMR/BNB,IOST/BNB,AGI/BNB,STRAT/ETH,DUSK/PAX,LRC/ETH,EDO/BTC,FTM/USDC,BCHABC/PAX,BCPT/ETH,ATOM/BNB,MFT/ETH,DOGE/BNB,GXS/ETH,ENG/ETH,SKY/ETH,NEO/TUSD,TFUEL/BNB,BAT/TUSD,TRX/TUSD,CMT/ETH,MITH/BNB,XLM/USDC,XLM/PAX,GTO/USDT,AST/ETH,NXS/BNB,DLT/ETH,GVT/ETH,BAT/PAX,FUN/ETH,NAS/ETH,WABI/ETH,DASH/BNB,QTUM/ETH,THETA/BNB,ARK/ETH,BCD/ETH,NULS/ETH,DLT/BNB,SYS/BNB,ETC/BNB,KMD/ETH,STEEM/BNB,WAN/BNB,APPC/ETH,BTT/USDC,ALGO/USDC,MCO/BNB,DGD/ETH,ALGO/TUSD,XEM/BNB,OMG/BNB,QKC/ETH,DNT/ETH,USDS/USDT,CVC/ETH,STORJ/ETH,LSK/BNB,BTT/TUSD,MFT/BNB,BTT/PAX,MTL/ETH,POE/ETH,TNB/ETH,IOTX/ETH,BNB/USDS,WABI/BNB,ETC/USDC,BCPT/BNB,QTUM/BNB,GTO/ETH,NAV/BNB,STEEM/ETH,DOCK/ETH,NAV/ETH,FTM/TUSD,VIA/BNB,CDT/ETH,QSP/ETH,XLM/TUSD,AMB/ETH,REQ/ETH,DCR/BNB,NAS/BNB,DOGE/USDC,CND/BNB,KEY/ETH,BTS/ETH,PIVX/ETH,OST/BNB,ZEN/BNB,ANKR/TUSD,AE/BNB,STORM/BNB,QLC/ETH,ONE/TUSD,APPC/BNB,ETC/TUSD,WAVES/TUSD,EDO/ETH,RLC/BNB,AMB/BNB,XZC/BNB,ANKR/USDC,WAVES/PAX,WAVES/USDC,GTO/TUSD,ERD/PAX,TFUEL/TUSD,BCPT/TUSD,PHB/PAX,ETC/PAX,BTC/USDT,BNB/BTC,ETH/BTC,EOS/USDT,PAX/USDT,REN/BTC,BCHABC/USDT,NANO/BTC,LTC/BTC,TRX/USDT,EOS/BTC,RVN/BTC,USDC/USDT,FTM/BTC,LINK/USDT,TRX/BTC,XMR/BTC,WTC/BTC,ETC/USDT,NEO/BTC,BAT/USDT,ALGO/BTC,FET/USDT,MATIC/BTC,ONT/USDT,MDA/BTC,NXS/BTC,BLZ/BTC,ONT/BTC,FTM/USDT,AION/BTC,XLM/USDT,IOTA/USDT,ICX/BTC,SKY/BTC,ZEC/BTC,EOS/ETH,MATIC/USDT,CELR/BTC,ATOM/BTC,QTUM/USDT,AST/BTC,THETA/BTC,DASH/BTC,WAVES/BTC,MCO/BTC,VET/BTC,LINK/ETH,PAX/TUSD,ZIL/BTC,BTG/BTC,XRP/ETH,CELR/USDT,RCN/BTC,HOT/USDT,USDC/TUSD,ZEC/USDT,BCPT/BTC,ETH/TUSD,GO/BTC,BAT/ETH,ADA/ETH,XRP/BNB,BQX/BTC,ADX/BTC,QKC/BTC,CND/BTC,TRX/XRP,GVT/BTC,ALGO/BNB,LUN/BTC,DOCK/BTC,USDC/PAX,TRX/BNB,BRD/BTC,XVG/BTC,IOST/BTC,DENT/BTC,MANA/BTC,ZIL/USDT,KNC/BTC,TFUEL/BTC,LTC/TUSD,ANKR/USDT,SNGLS/BTC,GXS/BTC,DCR/BTC,PHB/BTC,ELF/BTC,IOST/USDT,RDN/BTC,BTT/BNB,OMG/BTC,LTC/PAX,XEM/BTC,NPXS/ETH,ICX/ETH,HC/BTC,AE/BTC,LRC/BTC,CVC/BTC,DENT/ETH,MTH/BTC,THETA/USDT,NANO/ETH,QLC/BTC,ZEN/BTC,MATIC/BNB,ENJ/USDT,EOS/TUSD,BTC/USDS,IOTA/ETH,BNT/BTC,DUSK/BNB,BRD/BNB,POE/BTC,EOS/USDC,WPR/BTC,ZRX/USDT,AMB/BTC,WTC/ETH,NULS/USDT,POA/BTC,DOGE/BTC,BLZ/ETH,PIVX/BTC,QSP/BTC,RLC/BTC,BCD/BTC,NANO/BNB,MDA/ETH,NCASH/BTC,ZIL/ETH,SNT/BTC,BTS/BTC,ONT/ETH,ZIL/BNB,LEND/BTC,ETC/ETH,BAT/USDC,OMG/ETH,MFT/BTC,DATA/BTC,HOT/BNB,SC/BTC,ONT/BNB,ZRX/ETH,LEND/ETH,BTG/ETH,REP/BTC,XLM/BNB,NEBL/ETH,CDT/BTC,BLZ/BNB,NXS/ETH,WAVES/ETH,NEO/PAX,KEY/BTC,AE/ETH,AGI/ETH,ATOM/TUSD,IOST/ETH,ADX/ETH,STORM/BTC,SYS/ETH,SC/ETH,LINK/PAX,AION/BNB,WTC/BNB,CND/ETH,DUSK/USDC,ARDR/ETH,SNM/ETH,TRX/PAX,ZEC/ETH,WAVES/BNB,BNT/ETH,ENJ/BNB,LSK/ETH,LUN/ETH,TNT/ETH,RDN/ETH,XVG/ETH,NULS/BNB,MANA/ETH,ICX/BNB,OST/ETH,ZEC/USDC,USDS/PAX,ELF/ETH,XEM/ETH,NEBL/BNB,RCN/ETH,STORM/ETH,ZEC/BNB,ZRX/BNB,BQX/ETH,SNGLS/ETH,LOOM/ETH,VIA/ETH,POWR/ETH,XZC/ETH,GNT/ETH,FTM/PAX,ALGO/PAX,BRD/ETH,HC/ETH,USDS/USDC,VIBE/ETH,ARDR/BNB,VIB/ETH,ERD/USDC,GRS/ETH,NCASH/BNB,CVC/BNB,RLC/ETH,BTS/BNB,REP/ETH,RDN/BNB,ADX/BNB,BTCB/BTC,SNT/ETH,ONE/PAX,SC/BNB,ZEN/ETH,XZC/XRP,WPR/ETH,ZEC/TUSD,MTH/ETH,POA/ETH,ONE/USDC,POLY/BNB,GO/BNB,GNT/BNB,ZEC/PAX,USDS/TUSD,RCN/BNB,POWR/BNB,PIVX/BNB,ATOM/USDC,LOOM/BNB,PHB/BNB,INS/ETH,CMT/BNB,ATOM/PAX,PHB/TUSD,QSP/BNB,YOYO/ETH,DATA/ETH,ONG/BNB,SKY/BNB,POA/BNB,BCPT/PAX,QLC/BNB,REP/BNB,TFUEL/USDC,ANKR/PAX,YOYO/BNB,GTO/PAX,BCPT/USDC,PHB/USDC,TFUEL/PAX,GTO/USDC,DOGE/PAX".split(",")

def get_keys():
    with open('keys.json','r')as keys_file:
        data = json.load(keys_file)
        return data['api_secret'],data['api_key']



def get_coins():
    with open('pairs.json') as file:
        data = json.load(file)
        pairs = data['pairs']
        file.close()
    return pairs




example = ['BNB', 'BTC', 'NEBL']

markets = [p.split('/') for p in pairs]
markets = [m[0]+m[1] for m in markets]

def get_stages(seq):
    operation_type = lambda pair : [pair[0]+pair[1],'bids'] if pair[0]+pair[1] in markets else [pair[1]+pair[0],'asks']
    return [operation_type((seq[0],seq[1])),operation_type((seq[1],seq[2])),operation_type((seq[2],seq[0]))]

def deep_search(seq):
    get_book = lambda pair : client.get_order_book(symbol=pair[0])[pair[1]]
    step1, step2, step3 = get_stages(seq)
    price1 = get_book(step1)[0][0]
    time.sleep(0.5)
    price2 = get_book(step2)[0][0]
    time.sleep(0.5)
    price3 = get_book(step3)[0][0]
    return Decimal(price1)*1/Decimal(price2)*Decimal(price3)

def att_price():
    prices = client.get_orderbook_tickers()
    g.att_prices(prices)

def test_deep(seq):
    start = time.time()
    r = deep_search(seq)
    elapsed = time.time()-start
    print('book = '+ str(r))
    print(elapsed)



#api_key , api_secret = get_keys()
client = Client('', '')
bases = ['BTC']

def setup(bases):
    path = []
    g = graph.make_graph(pairs)
    for b in bases:
        path += g.generate_paths(b)
    return g,path



def test(sleep):
    g, path = setup(bases)
    i = 0
    while True:
        start_time1 = time.time()
        prices = client.get_orderbook_tickers()
        elapsed_time1 = time.time() - start_time1

        g.att_prices(prices)
        start_time = time.time()
        for p in path:
            v = g.calc_path(p)
            if  v > 1.0001 :
                print(p,'oportunidade de: '+str(float((v-1)*100))+'%')
            elapsed_time = time.time() - start_time
        print('request: %f, calc: %f' % (elapsed_time1,elapsed_time))
        time.sleep(sleep)
        i+=1

test(1)

